[package]
name = "reestream-server"
version = "0.2.0"
edition = "2024"
authors = ["RustLangES contact@rustlang-es.org"]
description = "HLS/HTTP streaming server and REST API"
license = "MIT OR Apache-2.0"

[features]
default = []
hls = ["dep:tower-http"]
api = []

[dependencies]
axum = "0.8"
bytes = "1.10"
reestream-core = { path = "../reestream-core" }
reqwest = { version = "0.12.24", default-features = false, features = [
    "json",
    "rustls-tls",
] }
rust-embed = "8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", default-features = false, features = [
    "io-util",
    "macros",
    "net",
    "process",
    "rt-multi-thread",
    "sync",
    "time",
    "fs",
] }
tower-http = { version = "0.6", features = ["cors"], optional = true }
tracing = { version = "0.1", features = ["log"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
